training: !!bool "true"
device: 14, 15 #gpu id
seed: 777
---
data:
    train_path: './dataVoxCeleb1/Audio/dev/processed'
    train_path_unprocessed: './dataVoxCeleb1/Audio/dev/wav' #*/wav/speaker_id/session_id/file.wav
    test_meta_path: './dataVoxCeleb1/Metadata/veri_test.txt'
    test_path: './dataVoxCeleb1/Audio/test/processed'
    test_path_unprocessed: './dataVoxCeleb1/Audio/test/wav'
    feat_type: 'spec' #feature type: 'spec' (spectogram), 'logmel' (logmel spectogram)
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 250 #Max number of time steps/frames in input after preprocess
---
model:
    type: 'TResNet34' 
    proj: 512 #Embedding size
    ghost_centers: 2
    vlad_centers: 8
    dropout: 0.0
    model_path: 'best.pth'
---
train:
    N: 160 #Number of speakers in batch
    M: 1 #Number of utterances per speaker
    num_workers: 16 
    lr: 0.001
    optim: 'Adam' #optimizer type: 'Adam' (lr 0.001), 'SGD', 'Adadelta' (lr 0.1)
    loss: 'si' #loss type: "si" (Speaker identification)
    warmup_epochs: 1 #number of warmup epochs with lr set to lr/10
    wd: 0.0001 #weight decay
    epochs: 128 #Max training epoch
    log_interval: 100 #Iterations before printing progress
    checkpoint_interval: 10 #test on sp. verification after #checkpoint_interval epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
